# Generated by Django 5.2.11 on 2026-04-09 07:21

from django.db import migrations


def populate_variants(apps, schema_editor):
    """
    For each OrderItem that has a product but no variant,
    create a default variant for that product (if it doesn't exist)
    and link the OrderItem to it.
    """
    Product = apps.get_model('products', 'Product')
    ProductVariant = apps.get_model('products', 'ProductVariant')
    OrderItem = apps.get_model('orders', 'OrderItem')

    for item in OrderItem.objects.filter(variant__isnull=True, product__isnull=False):
        variant, _ = ProductVariant.objects.get_or_create(
            product=item.product,
            is_main=True,
            defaults={
                'name': f'{item.product.name} - Default',
                'sku': f'MIGRATED-{item.product.pk}',
                'price': item.price,
                'stock': 0,
                'attributes': {},
                'is_active': True,
            },
        )
        item.variant = variant
        item.save(update_fields=['variant'])


def reverse_populate(apps, schema_editor):
    """Reverse: copy variant's product back to OrderItem.product."""
    OrderItem = apps.get_model('orders', 'OrderItem')
    for item in OrderItem.objects.filter(variant__isnull=False, product__isnull=True):
        item.product = item.variant.product
        item.save(update_fields=['product'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_variant_alter_orderitem_product'),
        ('products', '0002_remove_product_image_remove_product_price_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_variants, reverse_populate),
    ]
